require_relative 'html'

puts Html.make_tag('img', {src: 'bernie.jpg'}, :empty)
puts Html.make_tag('div', {id: 'root', class: 'frame'}, :sandwich)
puts Html.make_tag('Gallery', {}, :selfclose)
puts Html.make_tag('p', {style: 'color: red;'}, :sandwich)
puts Html.make_tag('input', {type: 'text', placeholder: 'Enter name'}, :selfclose)
puts Html.make_tag('a', {href: 'https://example.com', target: '_blank'}, :sandwich)
puts Html.make_tag('h1', {}, :sandwich)
puts Html.make_tag('hr', {}, :selfclose)
puts Html.make_tag('button', {type: 'submit'}, :sandwich)
puts Html.make_tag('section', {class: 'content'}, :sandwich)
puts Html.make_tag('br', {}, :selfclose)
puts Html.make_tag('span', {class: 'highlight'}, :sandwich)
puts Html.make_tag('ul', {}, :sandwich)
puts Html.make_tag('li', {class: 'item'}, :sandwich)
puts Html.make_tag('meta', {charset: 'UTF-8'}, :selfclose)
puts Html.make_tag('link', {rel: 'stylesheet', href: 'styles.css'}, :selfclose)
puts Html.make_tag('script', {src: 'script.js'}, :sandwich)
puts Html.make_tag('table', {border: '1'}, :sandwich)
puts Html.make_tag('tr', {}, :sandwich)
puts Html.make_tag('td', {}, :sandwich)
puts Html.make_tag('nav', {}, :sandwich)
puts Html.make_tag('footer', {}, :sandwich)
puts Html.make_tag('header', {}, :sandwich)